src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 */
class Contact
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Objet;

    /**
     * @ORM\Column(type="text")
     */
    private $Message;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $created;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getObjet(): ?string
    {
        return $this->Objet;
    }

    public function setObjet(string $Objet): self
    {
        $this->Objet = $Objet;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(string $Message): self
    {
        $this->Message = $Message;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(?\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }
}

src/Entity/Souscription.php
<?php

namespace App\Entity;

use App\Repository\SouscriptionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SouscriptionRepository::class)
 */
class Souscription
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="Souscription")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Offer::class, inversedBy="souscriptions")
     */
    private $Offer;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEtat(): ?int
    {
        return $this->etat;
    }

    public function setEtat(int $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getOffer(): ?Offer
    {
        return $this->Offer;
    }

    public function setOffer(?Offer $Offer): self
    {
        $this->Offer = $Offer;

        return $this;
    }

    public function __construct(?User $user,?Offer $Offer){
        $this->setEtat(1);
    }
}

templates/espace-client/add_information.html.twig
{% extends 'espace-client/layout.html.twig' %}

{% block title %}Hello Client!{% endblock %}

{% block body %}


    {{ form_start(form) }}
                    {{ form_widget(form) }}
                    <button class="btn">{{ button_label|default('Save') }}</button>
                    {{ form_end(form) }}


{% endblock %}

templates/espace-client/index.html.twig
{% extends 'espace-client/layout.html.twig' %}

{% block title %}Hello Client!{% endblock %}

{% block body %}

<div class="example-wrapper">
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <h1>Bienvenue {{ app.user.prenom}} {{ app.user.nom}}</h1>
    <h2> Voilà vos informations</h2>

    <table class="table">
        <tbody>
        <tr>
            <th>Mail</th>
            <td>{{ app.user.email }}</td>
        </tr>
        <tr>
            <th>Nom</th>
            <td>{{ app.user.nom ? app.user.nom : 'information manquante' }}</td>
        </tr>
        <tr>
            <th>Prenom</th>
            <td>{{ app.user.prenom ? app.user.prenom : 'information manquante' }}</td>
        </tr>
        <tr>
            <th>Genre</th>
            <td>{{ app.user.genre ? app.user.genre : 'information manquante' }}</td>
        </tr>
        <tr>
            <th>Date de naissance</th>
            <td>{{ app.user.dateNaissance ? app.user.dateNaissance|date('Y-m-d') : 'information manquante' }}</td>
        </tr>
        <tr>
            <th>Telephone</th>
            <td>{{ app.user.telephone ? app.user.telephone : 'information manquante' }}</td>
        </tr>
        <tr>
            <th>Ville</th>
            <td>{{ app.user.ville ? app.user.ville : 'information manquante' }}</td>
        </tr>
        <tr>
            <th>Code Postal</th>
            <td>{{ app.user.codePostal ? app.user.codePostal : 'information manquante' }}</td>
        </tr>
        <tr>
            <th>Pays</th>
            <td>{{ app.user.pays ? app.user.pays : 'information manquante' }}</td>
        </tr>
        <tr>
            <th>Numero de Securité Sociale</th>
            <td>{{ app.user.numSecu ? app.user.numSecu : 'information manquante' }}</td>
        </tr>
        </tbody>
    </table>
    <a href="{{ path('user_modify')}}">Editer profil</a></br>
</div>
{% endblock %}

templates/espace-client/layout.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace Client{% endblock %}

{% block logo %}
    <a class="navbar-brand" href="{{ path('admin')}}">
        <img src="{{asset('images/logo.jpg')}}" style="height: 110px;" alt="image">
    </a>
{% endblock %}

{% block header_links %}
    <div class="site_information">
        <ul>
            <li><a class="join_bt" href="{{ path('index') }}">Voir le site</a></li>
            <li><a class="join_bt" href="{{ path('app_logout')}}"> Déconnexion </a></li>

        </ul>
    </div>
{% endblock %}

{% block navbar_links %}
    <li><a class="nav-link active" href="{{ path('article_index')}}">Actualités</a></li>
    <li><a class="nav-link active" href="{{ path('user_home')}}">Utilisateur</a></li>
    <li><a class="nav-link active" href="{{ path('user_souscriptions')}}">Souscription</a></li>

{% endblock %}

{% block layout %}

    <!-- Start header -->
    <div class="section first">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    {% block body %}{% endblock %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/espace-client/souscription.html.twig
{% extends 'espace-client/layout.html.twig' %}

{% block title %}Souscription{% endblock %}

{% block body %}
    <h1>Souscription</h1>
    {% if souscription|length >0 %}

    {% for soursciptions in souscription %}

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ soursciptions.id }}</td>
        </tr>
        <tr>
            <th>Etat</th>
            <td>{{ soursciptions.etat }}</td>
        </tr>
        <tr>
            <th>Offer</th>
            <td>{{ soursciptions.offer.title }}</td>
        </tr>
        </tbody>
    </table>
{% endfor %}
    {% else %}

    <h2> Vous n'avez pas encore de Souscriptions</h2>
{% endif %}

{% endblock %}